blank_issues_enabled: false
contact_links:
  - name: 💬 CloudStream Resmi Topluluğu (Discord)
    url: https://discord.gg/5Hus6ur
    about: CloudStream genel sorunları ve uygulama içi yardım için Discord sunucusunu ziyaret edebilirsiniz.
